defmodule Kollywood.Publisher do
  @moduledoc """
  Behaviour for publishing agent work as a pull/merge request.

  Adapters use the platform's CLI tool (gh, glab) so that authentication
  is handled by the user's existing CLI setup rather than requiring API tokens
  in Kollywood's config.
  """

  alias Kollywood.Config
  alias Kollywood.Workspace

  @type pr_opts :: %{
          draft: boolean(),
          base_branch: String.t(),
          title: String.t(),
          body: String.t()
        }

  @doc """
  Creates a pull/merge request for the given workspace branch.
  Returns `{:ok, url}` on success or `{:error, reason}`.
  """
  @callback create_pr(Workspace.t(), pr_opts()) :: {:ok, String.t()} | {:error, String.t()}

  @doc """
  Returns the Publisher module for the given provider atom, or an error.
  """
  @spec module_for_provider(atom()) :: {:ok, module()} | {:error, String.t()}
  def module_for_provider(:github), do: {:ok, Kollywood.Publisher.GitHub}
  def module_for_provider(:gitlab), do: {:ok, Kollywood.Publisher.GitLab}

  def module_for_provider(other),
    do: {:error, "no publisher adapter for provider #{inspect(other)}"}

  @doc """
  Builds the PR options map from config and issue, with auto_create_pr policy applied.
  Returns `nil` if PR creation is disabled.
  """
  @spec pr_opts(Config.t(), map(), String.t() | nil) :: pr_opts() | nil
  def pr_opts(config, issue, last_output) do
    policy = get_in(config, [Access.key(:publish, %{}), Access.key(:auto_create_pr, :never)])

    case policy do
      :never ->
        nil

      draft_or_ready ->
        base_branch =
          get_in(config, [Access.key(:git, %{}), Access.key(:base_branch, "main")]) || "main"

        identifier = Map.get(issue, :identifier) || Map.get(issue, "identifier") || ""
        title = Map.get(issue, :title) || Map.get(issue, "title") || identifier

        %{
          draft: draft_or_ready == :draft,
          base_branch: base_branch,
          title: "#{identifier}: #{title}",
          body: pr_body(issue, last_output)
        }
    end
  end

  defp pr_body(issue, last_output) do
    identifier = Map.get(issue, :identifier) || Map.get(issue, "identifier") || ""
    description = Map.get(issue, :description) || Map.get(issue, "description") || ""

    output_section =
      if is_binary(last_output) and String.trim(last_output) != "" do
        trimmed = last_output |> String.trim() |> String.slice(0, 1000)
        "\n## Agent Summary\n\n#{trimmed}"
      else
        ""
      end

    """
    Closes #{identifier}

    #{String.trim(description)}#{output_section}

    ---
    *Generated by Kollywood*
    """
    |> String.trim()
  end
end
