defmodule Kollywood.Publisher do
  @moduledoc """
  Behaviour for publishing agent work as a pull/merge request.

  Adapters use the platform's CLI tool (gh, glab) so that authentication
  is handled by the user's existing CLI setup rather than requiring API tokens
  in Kollywood's config.
  """

  alias Kollywood.Config
  alias Kollywood.Workspace

  @type pr_opts :: %{
          draft: boolean(),
          base_branch: String.t(),
          title: String.t(),
          body: String.t()
        }

  @doc """
  Creates a pull/merge request for the given workspace branch.
  Returns `{:ok, url}` on success or `{:error, reason}`.
  """
  @callback create_pr(Workspace.t(), pr_opts()) :: {:ok, String.t()} | {:error, String.t()}

  @doc """
  Enables platform auto-merge for a pull/merge request.
  """
  @callback enable_auto_merge(Workspace.t(), String.t()) :: :ok | {:error, String.t()}

  @doc """
  Returns whether a pull/merge request has been merged.
  """
  @callback merged?(Workspace.t(), String.t()) ::
              {:ok, true} | {:ok, false} | {:error, String.t()}

  @doc """
  Returns the Publisher module for the given provider atom, or an error.
  """
  @spec module_for_provider(atom()) :: {:ok, module()} | {:error, String.t()}
  def module_for_provider(:github), do: {:ok, Kollywood.Publisher.GitHub}
  def module_for_provider(:gitlab), do: {:ok, Kollywood.Publisher.GitLab}

  def module_for_provider(other),
    do: {:error, "no publisher adapter for provider #{inspect(other)}"}

  @doc """
  Builds PR options from config + issue for modes that create PRs.
  Returns `nil` when mode does not require a PR.
  """
  @spec pr_opts(Config.t(), map()) :: pr_opts() | nil
  def pr_opts(config, issue) do
    mode = Config.effective_publish_mode(config)

    auto_create_pr =
      get_in(config, [Access.key(:publish, %{}), Access.key(:auto_create_pr, :never)])

    case mode do
      :push ->
        nil

      mode when mode in [:pr, :auto_merge] ->
        base_branch =
          get_in(config, [Access.key(:git, %{}), Access.key(:base_branch, "main")]) || "main"

        identifier = Map.get(issue, :identifier) || Map.get(issue, "identifier") || ""
        title = Map.get(issue, :title) || Map.get(issue, "title") || identifier

        %{
          draft: mode == :pr and auto_create_pr == :draft,
          base_branch: base_branch,
          title: "#{identifier}: #{title}",
          body: pr_body(issue)
        }
    end
  end

  defp pr_body(issue) do
    identifier = Map.get(issue, :identifier) || Map.get(issue, "identifier") || ""
    description = Map.get(issue, :description) || Map.get(issue, "description") || ""

    """
    Closes #{identifier}

    #{String.trim(description)}

    ---
    *Generated by Kollywood*
    """
    |> String.trim()
  end
end
