import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :kollywood, KollywoodWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is handled at the network level (Tailscale). No force_ssl needed.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
